[DEV-815] streambot js ts conversion
betterplace/streambot pull request #67
Opened 2022-12-13 15:27 UTC by katrinundfritz

2022-12-15 11:21 UTC, smnscp requested changes

2022-12-15 11:21 UTC, smnscp commented on src/tools/reloading.tsx
> +      const url = resolveToApiUrl(this.props.match, counter, perPage, this.state.since, this.state.hashtags)
```suggestion
      const url = resolveToApiUrl(this.props.match, counter, perPage, this.state.since, this.state.hashtags)
      if (!url) return
```

2022-12-15 11:21 UTC, smnscp commented on src/tools/reloading.tsx
> +        }
With above guard clause we can revert this.
```suggestion
        fetch(url)
          .then((response) => response.json())
          .then((json) => this.storeData(json))
          .then(undefined, (err) => console.log(err))
```

2022-12-15 11:43 UTC, smnscp requested changes
I’d suggest a uniform way for using `parseInt` in combination with `params.get`.

2022-12-15 11:43 UTC, smnscp commented on src/components/ProjectCarrierLogos.tsx
> +      duration: parseInt(params.get('duration') as string) || 5,
```suggestion
      duration: parseInt(params.get('duration') || '') || 5,
```

2022-12-15 11:43 UTC, smnscp commented on src/tools/reloading.tsx
> +        interval: params.get('interval') ? parseInt(params.get('interval') as string, 10) : 3,
```suggestion
        maxCount: parseInt(params.get('maxCount') || '', 10) || 1,
        interval: parseInt(params.get('interval') || '', 10) || 3,
```

2022-12-15 11:43 UTC, smnscp commented on src/tools/styled.tsx
> +  return (params.has(name) && parseInt(params.get(name) as string, 10)) || defaultValue
```suggestion
  return parseInt(params.get(name) || '', 10) || defaultValue
```

2022-12-15 11:43 UTC, smnscp commented on src/components/LastComment.tsx
> +      <div className="truncate-with-ellipsis">{maxLength ? truncate(message, parseInt(maxLength)) : message}</div>
```suggestion
  const maxLength = parseInt(props.params.get('maxLength') || '')

  return (
    <div className="truncate-with-ellipsis">
      <div className="truncate-with-ellipsis">{truncate(message, maxLength)}</div>
```

2022-12-15 11:56 UTC, katrinundfritz commented on src/components/LastComment.tsx
> +      <div className="truncate-with-ellipsis">{maxLength ? truncate(message, parseInt(maxLength)) : message}</div>
Wouldn't truncate(message, 0) then result in an non-existing message? If maxLength is not set we want to show the whole message and not truncate it.

2022-12-15 12:00 UTC, smnscp commented on src/components/LastComment.tsx
> +      <div className="truncate-with-ellipsis">{maxLength ? truncate(message, parseInt(maxLength)) : message}</div>
`truncate` with `0|NaN` returns the whole message.

2022-12-15 12:13 UTC, katrinundfritz commented on src/components/LastComment.tsx
> +      <div className="truncate-with-ellipsis">{maxLength ? truncate(message, parseInt(maxLength)) : message}</div>
You are right. I tried it out. 🥇

2022-12-15 12:34 UTC, josefie requested changes

2022-12-15 12:34 UTC, josefie commented on src/tools/reloading.tsx
> +        interval: params.get('interval') ? parseInt(params.get('interval') as string, 10) : 3,
I just had a similar thought.
I don't think casting to a string makes sense here, because it actually can be null. My idea was to put the fallback case inside of parseInt instead? (It's kinda weird to add it as a string just to parse it back to an integer again, though)

```suggestion
        maxCount: parseInt(params.get('maxCount') || '1', 10),
        interval: parseInt(params.get('interval') || '3', 10),
```

2022-12-15 12:34 UTC, josefie commented on src/components/Hashtags.tsx
> +}: {data: any}) => {
Can we make sure data is always an object?

2022-12-15 12:34 UTC, josefie commented on src/components/Hashtags.tsx
> +  const entries = Object.entries(data) as [[key: string, value: string | number]]
Hmm above (`const counts: number[] = Object.values(data)`) it looks like the values should always be numbers... 🤔 Why can they be strings or numbers now?

2022-12-15 12:43 UTC, katrinundfritz commented on package.json
> +    "@types/jest": "^29.2.4",
Without @types/jest `src/tools/__tests__/buildGoogleWebfontUrl.test.ts` was yelling at me. But maybe there is an other more appropriate type package to include?!?

2022-12-15 12:48 UTC, katrinundfritz commented on src/components/Hashtags.tsx
> +  const entries = Object.entries(data) as [[key: string, value: string | number]]
You are right. Number is fine. I will remove string.

2022-12-15 13:08 UTC, smnscp commented on package.json
> +    "ts-migrate": "^0.1.35",
Once we’re done with this don’t forget to remove the dependency again.

2022-12-15 13:49 UTC, katrinundfritz commented on src/components/Hashtags.tsx
> +}: {data: any}) => {
Resolved for Hashtags.

2022-12-15 13:54 UTC, josefie commented on package.json
> +    "@types/jest": "^29.2.4",
Ok, I understand now: `react-scripts` uses `jest` under the hood. And they also add this package in their installation guide: https://create-react-app.dev/docs/adding-typescript/ so that's fine.

2022-12-15 13:57 UTC, josefie approved these changes

2022-12-16 13:02 UTC, smnscp requested changes
Found one last issue. Otherwise approved.

2022-12-16 13:03 UTC, smnscp approved these changes

2022-12-16 13:12 UTC, josefie requested changes

2022-12-16 13:12 UTC, josefie commented on src/components/preconfigured/Standard.tsx
> +  eventId?: number
Shouldn't this be required? I guess the URL doesn't make sense without an id...

2022-12-16 13:12 UTC, josefie commented on src/tools/reloading.tsx
> +const resolveToApiUrl = (match: any, counter: number, perPage: number, since = '', hashtags: string | null = null) => {
I guess `since` is a string?

2022-12-16 13:15 UTC, katrinundfritz commented on src/tools/reloading.tsx
> +const resolveToApiUrl = (match: any, counter: number, perPage: number, since = '', hashtags: string | null = null) => {
Yes. But Typescript is so smart to know this because we do the assignment to ''. So if I say since: string = '' it tells me that I should not declare it. It's inferred.

2022-12-16 15:47 UTC, katrinundfritz commented on src/components/DonationList.tsx
> +            <Donation key={donation.id} {...donation} params={props.match.params} />
I had another look and it seems like params is not used in the Donation Component. So we might want to remove it.
```suggestion
            <Donation key={donation.id} {...donation} />
```

2022-12-16 16:08 UTC, katrinundfritz commented on src/components/DonationList.tsx
> +            <Donation key={donation.id} {...donation} params={props.match.params} />
Maybe it was meant to replace `{formatCents(cents, new URLSearchParams())}` at one point but then the work on the feature was stopped.

2022-12-16 16:32 UTC, josefie requested changes

2022-12-16 16:32 UTC, josefie commented on src/components/DonationList.tsx
> +            <Donation key={donation.id} {...donation} params={props.match.params} />
If it's not used at all, sure!

2022-12-16 16:32 UTC, josefie commented on src/components/List.tsx
> +type ListProps = Pick<ReloadingWidgetProps, 'params'> & { simple: string; listData: ListData[] }
`simple` was a boolean before (which is correct, I think)
https://github.com/betterplace/streambot/commit/2af89cf091e6fbd93c13bbcab806726daabb02ef#diff-f9443d16b37d98498c536a8043114094b79f897717c811be0a3ba7425f786f8dR6

2022-12-19 08:16 UTC, josefie approved these changes

2022-12-19 13:31 UTC, merged